name: samm-pdf-builder
on: push
jobs:
    build-pdf:
        runs-on: ubuntu-latest
        steps:
        - name: "checkout datafiles"
          uses: actions/checkout@v2

        - name: "create output directory"
          run: |
            mkdir ${{ github.workspace }}/output

        - name: "process datafiles"
          uses: docker://nessimk/samm2cloudpdf:0.12
          with:
            args: "/github/workspace/static /github/workspace/datafiles /github/workspace/output"

        - name: "rename pdf"
          run: |
            sudo mv ${{ github.workspace  }}/output/pdf/samm2.pdf ${{ github.workspace }}/output/pdf/samm2-${{ github.sha  }}.pdf

        - name: "save generated html"
          run: |
            sudo cp -r  ${{ github.workspace }}/output/html ${{ github.workspace  }}/output/pdf/generated-html-${{ github.sha  }}

        - name: "upload pdf"
          uses: actions/upload-artifact@v2
          with:
            name: samm2-${{ github.sha  }}.pdf
            path: ${{ github.workspace }}/output/pdf/

        - name: "upload generated html"
          uses: actions/upload-artifact@v2
          with:
            name: generated-html-${{ github.sha  }}
            path: ${{ github.workspace }}/output/pdf/
